/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uas.Koneksi;
/**
 *
 * @author Acer
 */
public class ukt extends javax.swing.JFrame {
Koneksi myObject;
  public DefaultTableModel modelTabelBooking;
    public ukt() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        myObject = new Koneksi();
        modelTabelBooking = new DefaultTableModel();
        jTable1.setModel(modelTabelBooking);
        modelTabelBooking.addColumn("No UKT");
        modelTabelBooking.addColumn("NPM");
        modelTabelBooking.addColumn("NAMA MAHASISWA");
        modelTabelBooking.addColumn("KETERANGAN");
        tampilDataBooking();
    }
    
    public void tampilDataBooking(){
        try {
            modelTabelBooking.getDataVector().removeAllElements();
            modelTabelBooking.fireTableDataChanged();
        
            PreparedStatement query = myObject.Konek.prepareStatement("SELECT * FROM ukt");
            ResultSet data = query.executeQuery();
            while (data.next()) {
            Object[] baris = new Object[4];
            baris[0] = data.getString("no_ukt");
            baris[1] = data.getString("npm");
            baris[2] = data.getString("nama_mahasiswa");
            baris[3] = data.getString("keterangan");
            modelTabelBooking.addRow(baris);
            
            }
            query.close();
            data.close();
            } catch (Exception e){
            }
        
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(51, 0, 204));
        jCheckBox1.setText("BULAN 1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 85, -1));

        jCheckBox2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(51, 0, 204));
        jCheckBox2.setText("BULAN 2");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 85, -1));

        jCheckBox3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(51, 0, 204));
        jCheckBox3.setText("BULAN 3");
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 85, -1));

        jCheckBox4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(51, 0, 204));
        jCheckBox4.setText("LANGSUNG LUNAS");
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 149, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("NO UKT         :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Npm                  ;");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("NAMA MAHASISWA     :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 180, -1));

        jTextField1.setBackground(new java.awt.Color(153, 0, 0));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 320, -1));

        jTextField2.setBackground(new java.awt.Color(153, 0, 0));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 320, -1));

        jTextField3.setBackground(new java.awt.Color(153, 0, 0));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(242, 242, 242));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 260, -1));

        jTable1.setBackground(new java.awt.Color(153, 153, 0));
        jTable1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 0, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 170, 660, 260));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(242, 242, 242));
        jButton3.setText("HAPUS");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 255, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(242, 242, 242));
        jButton5.setText("<--");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // Logika penyimpanan data
        // Konfigurasi koneksi database
        String url = "jdbc:mysql://localhost:3306/krs";
        String username = "root";
        String password = "";

        try {
            // Membuat koneksi
            Connection connection = DriverManager.getConnection(url, username, password);

            // Inisialisasi nilai default
            String harga1 = "Rp.1.500.000";
            String harga2 = "Rp.867.000";
            String harga3 = "Rp.867.000";
            String lunas = "Lunas";

            // Menggunakan PreparedStatement untuk mencegah SQL Injection
            String query = "INSERT INTO ukt (no_ukt, npm, nama_mahasiswa, keterangan) VALUES (?, ?, ?, ?)";
            PreparedStatement preparedStatement = connection.prepareStatement(query);

            // Set nilai parameter PreparedStatement
            preparedStatement.setString(1, jTextField1.getText()); // Ambil nilai dari JTextField1 (no_ukt)
            preparedStatement.setString(2, jTextField2.getText()); // Ambil nilai dari JTextField2 (npm)
            preparedStatement.setString(3, jTextField3.getText()); // Ambil nilai dari JTextField3 (nama_mahasiswa)

            // Ambil nilai checkbox yang dipilih dan sesuaikan dengan kolom 'keterangan'
            StringBuilder keterangan = new StringBuilder();
            if (jCheckBox1.isSelected()) {
                keterangan.append(harga1);
            }
            if (jCheckBox2.isSelected()) {
                if (keterangan.length() > 0) {
                    keterangan.append(", ");
                }
                keterangan.append(harga2);
            }
            if (jCheckBox3.isSelected()) {
                if (keterangan.length() > 0) {
                    keterangan.append(", ");
                }
                keterangan.append(harga3);
            }
            if (jCheckBox4.isSelected()) {
                if (keterangan.length() > 0) {
                    keterangan.append(", ");
                }
                keterangan.append(lunas);
            }

            preparedStatement.setString(4, keterangan.toString()); // Set nilai kolom 'keterangan'

            // Eksekusi query
            preparedStatement.executeUpdate();

            System.out.println("Data berhasil disimpan ke tabel ukt di database krs.");

            // Tutup koneksi
            preparedStatement.close();
            connection.close();

        } catch (SQLException e) {
            e.printStackTrace();
               
        }
        tampilDataBooking();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        String no_ukt = jTable1.getValueAt(baris, 0).toString();
        String npm = jTable1.getValueAt(baris, 1).toString();
        String nama_mahasiswa = jTable1.getValueAt(baris, 2).toString();
        jTextField1.setText(no_ukt);
        jTextField2.setText(npm);
        jTextField3.setText(nama_mahasiswa);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String url = "jdbc:mysql://localhost:3306/krs";
    String username = "root";
    String password = "";
        try {
        // Membuat koneksi
        Connection connection = DriverManager.getConnection(url, username, password);

        // Menggunakan PreparedStatement untuk mencegah SQL Injection
        String query = "UPDATE ukt SET npm = ?, nama_mahasiswa = ?, keterangan = ? WHERE no_ukt = ?";
        PreparedStatement preparedStatement = connection.prepareStatement(query);

        // Set nilai parameter PreparedStatement
        preparedStatement.setString(1, jTextField2.getText()); // Ambil nilai dari JTextField2 (npm)
        preparedStatement.setString(2, jTextField3.getText()); // Ambil nilai dari JTextField3 (nama_mahasiswa)

        // Ambil nilai checkbox yang dipilih dan sesuaikan dengan kolom 'keterangan'
        StringBuilder keterangan = new StringBuilder();
        if (jCheckBox1.isSelected()) {
            keterangan.append("Rp.1.500.000");
        }
        if (jCheckBox2.isSelected()) {
            if (keterangan.length() > 0) {
                keterangan.append(", ");
            }
            keterangan.append("Rp.867.000");
        }
        if (jCheckBox3.isSelected()) {
            if (keterangan.length() > 0) {
                keterangan.append(", ");
            }
            keterangan.append("Rp.867.000");
        }
        if (jCheckBox4.isSelected()) {
            if (keterangan.length() > 0) {
                keterangan.append(", ");
            }
            keterangan.append("Lunas");
        }

        preparedStatement.setString(3, keterangan.toString()); // Set nilai kolom 'keterangan'
        preparedStatement.setString(4, jTextField1.getText()); // Ambil nilai dari JTextField1 (no_ukt)

        // Eksekusi query
        int rowCount = preparedStatement.executeUpdate();

        // Tutup koneksi
        preparedStatement.close();
        connection.close();

        // Cek apakah ada baris yang diupdate
        if (rowCount > 0) {
            System.out.println("Data berhasil diupdate di tabel ukt di database krs.");
            // Setelah update, tampilkan kembali data pada tabel
            tampilDataBooking();
        } else {
            System.out.println("Tidak ada data yang diupdate.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
    
    }
    tampilDataBooking();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       //kodingan hapus
        try {
    if (jTextField1.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "KODE belum di isi");
        jTextField1.requestFocus();
    } else {
        String sql = "DELETE FROM ukt WHERE no_ukt=?";
        try (PreparedStatement preparedStatement = myObject.Konek.prepareStatement(sql)) {
            preparedStatement.setString(1, jTextField1.getText());

            int rowsDeleted = preparedStatement.executeUpdate();

            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                tampilDataBooking();
            } else {
                JOptionPane.showMessageDialog(this, "Tidak ada data dengan KODE tersebut");
            }
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.toString());
}
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
          new dasbord().setVisible(true);
         dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             jTextField1.setText("");
        jTextField2.setText("");
      jTextField3.setText("");
      
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ukt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ukt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ukt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ukt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ukt().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
